#!/usr/bin/env python

from __future__ import print_function
import sys
import os

STASHFILE_PATH = os.path.join(os.getenv('HOME'), '.stashfile')
SEP = '|'
USAGE = """NAME
    stash - Persistent shell variables and values accross sessions.

SYNOPSIS
    stash <key> <value>
    <value> | stash [<key>] --stdin
    stash <key>
    stash --help
    stash --list
    stash --clear
    stash --pop

DESCRIPTION

"""

def main():
    # read from stash file
    try:
        with open(STASHFILE_PATH) as f:
            stash = {}
            for line in f:
                parts = line.strip().split(SEP, 1)
                stash[parts[0]] = parts[1]
    except:
        stash = {}

    # parse arguments
        # parse arguments
    nargs = len(sys.argv) - 1
    if nargs == 0:
        print(USAGE)
    elif nargs == 1:
        arg = sys.argv[1]
        if arg == '--help':
            print(USAGE)
        elif arg == '--list':
            print('\n'.join(map(str, stash.keys())))
        elif arg == '--clear':
            print("Are you sure (y/n): ", end='')
            if raw_input().strip() == 'y':
                stash = {}
                print('Cleared')
        else:
            print(stash.get(arg, ''), end='')
    elif nargs >= 2:
        pass

    # write back to file
    with open(STASHFILE_PATH, 'w') as f:
        f.write('\n'.join(k + SEP + v.replace('\\', '\\\\')
                          for k, v in stash.items()))

if __name__ == '__main__':
    main()
